// Code generated by MockGen. DO NOT EDIT.
// Source: account_abstraction/account_abstraction.go

// Package mock_accountabstraction is a generated GoMock package.
package mock_accountabstraction

import (
	context "context"
	big "math/big"
	reflect "reflect"

	app "github.com/anyproto/any-sync/app"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountAbstractionService is a mock of AccountAbstractionService interface.
type MockAccountAbstractionService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountAbstractionServiceMockRecorder
}

// MockAccountAbstractionServiceMockRecorder is the mock recorder for MockAccountAbstractionService.
type MockAccountAbstractionServiceMockRecorder struct {
	mock *MockAccountAbstractionService
}

// NewMockAccountAbstractionService creates a new mock instance.
func NewMockAccountAbstractionService(ctrl *gomock.Controller) *MockAccountAbstractionService {
	mock := &MockAccountAbstractionService{ctrl: ctrl}
	mock.recorder = &MockAccountAbstractionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountAbstractionService) EXPECT() *MockAccountAbstractionServiceMockRecorder {
	return m.recorder
}

// GetNamesCountLeft mocks base method.
func (m *MockAccountAbstractionService) GetNamesCountLeft(scw common.Address) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamesCountLeft", scw)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNamesCountLeft indicates an expected call of GetNamesCountLeft.
func (mr *MockAccountAbstractionServiceMockRecorder) GetNamesCountLeft(scw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamesCountLeft", reflect.TypeOf((*MockAccountAbstractionService)(nil).GetNamesCountLeft), scw)
}

// GetNonceForSmartWalletAddress mocks base method.
func (m *MockAccountAbstractionService) GetNonceForSmartWalletAddress(ctx context.Context, scw common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNonceForSmartWalletAddress", ctx, scw)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNonceForSmartWalletAddress indicates an expected call of GetNonceForSmartWalletAddress.
func (mr *MockAccountAbstractionServiceMockRecorder) GetNonceForSmartWalletAddress(ctx, scw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNonceForSmartWalletAddress", reflect.TypeOf((*MockAccountAbstractionService)(nil).GetNonceForSmartWalletAddress), ctx, scw)
}

// GetOperationsCountLeft mocks base method.
func (m *MockAccountAbstractionService) GetOperationsCountLeft(scw common.Address) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationsCountLeft", scw)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperationsCountLeft indicates an expected call of GetOperationsCountLeft.
func (mr *MockAccountAbstractionServiceMockRecorder) GetOperationsCountLeft(scw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationsCountLeft", reflect.TypeOf((*MockAccountAbstractionService)(nil).GetOperationsCountLeft), scw)
}

// GetSmartWalletAddress mocks base method.
func (m *MockAccountAbstractionService) GetSmartWalletAddress(eoa common.Address) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSmartWalletAddress", eoa)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSmartWalletAddress indicates an expected call of GetSmartWalletAddress.
func (mr *MockAccountAbstractionServiceMockRecorder) GetSmartWalletAddress(eoa interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSmartWalletAddress", reflect.TypeOf((*MockAccountAbstractionService)(nil).GetSmartWalletAddress), eoa)
}

// Init mocks base method.
func (m *MockAccountAbstractionService) Init(a *app.App) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockAccountAbstractionServiceMockRecorder) Init(a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockAccountAbstractionService)(nil).Init), a)
}

// MintAccessTokens mocks base method.
func (m *MockAccountAbstractionService) MintAccessTokens(scw common.Address, amount *big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MintAccessTokens", scw, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// MintAccessTokens indicates an expected call of MintAccessTokens.
func (mr *MockAccountAbstractionServiceMockRecorder) MintAccessTokens(scw, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MintAccessTokens", reflect.TypeOf((*MockAccountAbstractionService)(nil).MintAccessTokens), scw, amount)
}

// Name mocks base method.
func (m *MockAccountAbstractionService) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAccountAbstractionServiceMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAccountAbstractionService)(nil).Name))
}

// VerifyAdminIdentity mocks base method.
func (m *MockAccountAbstractionService) VerifyAdminIdentity(payload, signature []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAdminIdentity", payload, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyAdminIdentity indicates an expected call of VerifyAdminIdentity.
func (mr *MockAccountAbstractionServiceMockRecorder) VerifyAdminIdentity(payload, signature interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAdminIdentity", reflect.TypeOf((*MockAccountAbstractionService)(nil).VerifyAdminIdentity), payload, signature)
}
