// Code generated by MockGen. DO NOT EDIT.
// Source: client/client.go
//
// Generated by this command:
//
//	mockgen -source=client/client.go
//
// Package mock_client is a generated GoMock package.
package mock_client

import (
	context "context"
	reflect "reflect"

	anyns_api "github.com/anyproto/any-ns-node/pb/anyns_api"
	app "github.com/anyproto/any-sync/app"
	gomock "go.uber.org/mock/gomock"
)

// MockAnyNsClientService is a mock of AnyNsClientService interface.
type MockAnyNsClientService struct {
	ctrl     *gomock.Controller
	recorder *MockAnyNsClientServiceMockRecorder
}

// MockAnyNsClientServiceMockRecorder is the mock recorder for MockAnyNsClientService.
type MockAnyNsClientServiceMockRecorder struct {
	mock *MockAnyNsClientService
}

// NewMockAnyNsClientService creates a new mock instance.
func NewMockAnyNsClientService(ctrl *gomock.Controller) *MockAnyNsClientService {
	mock := &MockAnyNsClientService{ctrl: ctrl}
	mock.recorder = &MockAnyNsClientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnyNsClientService) EXPECT() *MockAnyNsClientServiceMockRecorder {
	return m.recorder
}

// AdminFundUserAccount mocks base method.
func (m *MockAnyNsClientService) AdminFundUserAccount(ctx context.Context, in *anyns_api.AdminFundUserAccountRequestSigned) (*anyns_api.OperationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminFundUserAccount", ctx, in)
	ret0, _ := ret[0].(*anyns_api.OperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminFundUserAccount indicates an expected call of AdminFundUserAccount.
func (mr *MockAnyNsClientServiceMockRecorder) AdminFundUserAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminFundUserAccount", reflect.TypeOf((*MockAnyNsClientService)(nil).AdminFundUserAccount), ctx, in)
}

// Close mocks base method.
func (m *MockAnyNsClientService) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAnyNsClientServiceMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAnyNsClientService)(nil).Close), ctx)
}

// GetNameByAddress mocks base method.
func (m *MockAnyNsClientService) GetNameByAddress(ctx context.Context, in *anyns_api.NameByAddressRequest) (*anyns_api.NameByAddressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNameByAddress", ctx, in)
	ret0, _ := ret[0].(*anyns_api.NameByAddressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNameByAddress indicates an expected call of GetNameByAddress.
func (mr *MockAnyNsClientServiceMockRecorder) GetNameByAddress(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNameByAddress", reflect.TypeOf((*MockAnyNsClientService)(nil).GetNameByAddress), ctx, in)
}

// GetOperation mocks base method.
func (m *MockAnyNsClientService) GetOperation(ctx context.Context, in *anyns_api.GetOperationStatusRequest) (*anyns_api.OperationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperation", ctx, in)
	ret0, _ := ret[0].(*anyns_api.OperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperation indicates an expected call of GetOperation.
func (mr *MockAnyNsClientServiceMockRecorder) GetOperation(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperation", reflect.TypeOf((*MockAnyNsClientService)(nil).GetOperation), ctx, in)
}

// GetOperationStatus mocks base method.
func (m *MockAnyNsClientService) GetOperationStatus(ctx context.Context, in *anyns_api.GetOperationStatusRequest) (*anyns_api.OperationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationStatus", ctx, in)
	ret0, _ := ret[0].(*anyns_api.OperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperationStatus indicates an expected call of GetOperationStatus.
func (mr *MockAnyNsClientServiceMockRecorder) GetOperationStatus(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationStatus", reflect.TypeOf((*MockAnyNsClientService)(nil).GetOperationStatus), ctx, in)
}

// GetUserAccount mocks base method.
func (m *MockAnyNsClientService) GetUserAccount(ctx context.Context, in *anyns_api.GetUserAccountRequest) (*anyns_api.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccount", ctx, in)
	ret0, _ := ret[0].(*anyns_api.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccount indicates an expected call of GetUserAccount.
func (mr *MockAnyNsClientServiceMockRecorder) GetUserAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccount", reflect.TypeOf((*MockAnyNsClientService)(nil).GetUserAccount), ctx, in)
}

// Init mocks base method.
func (m *MockAnyNsClientService) Init(a *app.App) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockAnyNsClientServiceMockRecorder) Init(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockAnyNsClientService)(nil).Init), a)
}

// IsNameAvailable mocks base method.
func (m *MockAnyNsClientService) IsNameAvailable(ctx context.Context, in *anyns_api.NameAvailableRequest) (*anyns_api.NameAvailableResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNameAvailable", ctx, in)
	ret0, _ := ret[0].(*anyns_api.NameAvailableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsNameAvailable indicates an expected call of IsNameAvailable.
func (mr *MockAnyNsClientServiceMockRecorder) IsNameAvailable(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNameAvailable", reflect.TypeOf((*MockAnyNsClientService)(nil).IsNameAvailable), ctx, in)
}

// Name mocks base method.
func (m *MockAnyNsClientService) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAnyNsClientServiceMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAnyNsClientService)(nil).Name))
}

// NameRegister mocks base method.
func (m *MockAnyNsClientService) NameRegister(ctx context.Context, in *anyns_api.NameRegisterRequest) (*anyns_api.OperationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NameRegister", ctx, in)
	ret0, _ := ret[0].(*anyns_api.OperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NameRegister indicates an expected call of NameRegister.
func (mr *MockAnyNsClientServiceMockRecorder) NameRegister(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NameRegister", reflect.TypeOf((*MockAnyNsClientService)(nil).NameRegister), ctx, in)
}

// NameRegisterSigned mocks base method.
func (m *MockAnyNsClientService) NameRegisterSigned(ctx context.Context, in *anyns_api.NameRegisterSignedRequest) (*anyns_api.OperationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NameRegisterSigned", ctx, in)
	ret0, _ := ret[0].(*anyns_api.OperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NameRegisterSigned indicates an expected call of NameRegisterSigned.
func (mr *MockAnyNsClientServiceMockRecorder) NameRegisterSigned(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NameRegisterSigned", reflect.TypeOf((*MockAnyNsClientService)(nil).NameRegisterSigned), ctx, in)
}

// NameRenew mocks base method.
func (m *MockAnyNsClientService) NameRenew(ctx context.Context, in *anyns_api.NameRenewRequest) (*anyns_api.OperationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NameRenew", ctx, in)
	ret0, _ := ret[0].(*anyns_api.OperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NameRenew indicates an expected call of NameRenew.
func (mr *MockAnyNsClientServiceMockRecorder) NameRenew(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NameRenew", reflect.TypeOf((*MockAnyNsClientService)(nil).NameRenew), ctx, in)
}

// Run mocks base method.
func (m *MockAnyNsClientService) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockAnyNsClientServiceMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockAnyNsClientService)(nil).Run), ctx)
}
